Update jobs for s390x

diff --git a/config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml b/config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
--- a/config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
+++ b/config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
@@ -1,58 +1,21 @@
 periodics:
-  - name: periodic-kubernetes-unit-test-ppc64le
-    cluster: k8s-ppc64le-cluster
-    decorate: true
-    decoration_config:
-      gcs_configuration:
-        bucket: ppc64le-kubernetes
-        path_strategy: explicit
-      gcs_credentials_secret: gcs-credentials
+  - name: periodic-kubernetes-unit-test-s390x
     cron: "0 1/3 * * *"
+    labels: 
+      preset-unit-test: "true"
     extra_refs:
-      - org: kubernetes
-        repo: kubernetes
-        base_ref: master
-        path_alias: k8s.io/kubernetes
-    spec:
-      securityContext:
-        runAsGroup: 2010
-        runAsUser: 2001
-      containers:
-        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250227-3a13bdd784-master
-          command:
-            - make
-            - test
-          securityContext:
-            allowPrivilegeEscalation: false
-          resources:
-            requests:
-              cpu: 4
-            limits:
-              cpu: 4
-  - name: periodic-kubernetes-unit-test-root-ppc64le
-    cluster: k8s-ppc64le-cluster
-    labels:
-      preset-golang-build: "true"
-    decorate: true
-    decoration_config:
-      gcs_configuration:
-        bucket: ppc64le-kubernetes
-        path_strategy: explicit
-      gcs_credentials_secret: gcs-credentials
-    cron: "0 0 * * 1,4"
-    extra_refs:
-      - base_ref: master
-        org: kubernetes
-        repo: kubernetes
+      - base_ref: add-s390x-prov
+        org: linux-on-ibm-z
+        repo: kubetest2-plugins
         workdir: true
     spec:
       containers:
-        - image: quay.io/powercloud/all-in-one:0.7
+        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20241128-8df65c072f-master
           resources:
             requests:
-              cpu: "5000m"
+              cpu: "1500m"
             limits:
-              cpu: "5000m"
+              cpu: "1500m"
           command:
             - /bin/bash
           args:
@@ -63,28 +26,58 @@ periodics:
               set -o pipefail
               set -o xtrace
 
-              export KUBE_TIMEOUT='--timeout=600s'
-              export KUBE_KEEP_VERBOSE_TEST_OUTPUT=y
-              export LOG_LEVEL=4
-              make test KUBE_RACE=-race
-  - name: periodic-kubernetes-containerd-conformance-test-ppc64le
+              export PATH=$GOPATH/bin:$PATH
+              export GO111MODULE=on
+
+              make install-deployer-tf
+
+              TF_LATEST="v1.9.8"
+
+              curl -fsSL https://releases.hashicorp.com/terraform/${TF_LATEST:1}/terraform_${TF_LATEST:1}_linux_amd64.zip -o ./terraform.zip
+              unzip -o ./terraform.zip  >/dev/null 2>&1
+              rm -f ./terraform.zip
+              TF="$PWD/terraform"
+              export PATH=$PWD:$PATH
+
+              apt-get update && apt-get install -y ansible
+
+              TIMESTAMP=$(date +%s)
+
+              set +o errexit
+              kubetest2 tf --target-provider vpc --vpc-node-image-name ibm-ubuntu-22-04-4-minimal-s390x-3 \
+                --vpc-region eu-de --vpc-zone eu-de-1 \
+                --vpc-name unit-tests-vpc \
+                --vpc-resource-group rg-unit-test \
+                --vpc-ssh-key k8s-unit-test \
+                --vpc-node-profile bz2-4x16 \
+                --ssh-private-key /etc/secret-volume/ssh-privatekey \
+                --cluster-name config4-$TIMESTAMP \
+                --up --set-kubeconfig=false --auto-approve \
+                --retry-on-tf-failure 3 \
+                --break-kubetest-on-upfail true \
+                --playbook k8s-ut-remote.yml
+              EXTERNAL_IP=`grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' $(pwd)/config4-$TIMESTAMP/hosts`
+              kubetest2 tf --target-provider vpc --test=exec -- ssh -i /etc/secret-volume/ssh-privatekey root@$EXTERNAL_IP \
+                "/make-test.sh"; \
+                rc=$?; scp -r -i /etc/secret-volume/ssh-privatekey root@$EXTERNAL_IP:/home/nonroot/artifacts $ARTIFACTS
+              kubetest2 tf --target-provider vpc --vpc-region eu-de --vpc-zone eu-de-1 \
+                --ignore-cluster-dir true \
+                --cluster-name config4-$TIMESTAMP \
+                --down --auto-approve --ignore-destroy-errors
+              [ $rc != 0 ] && echo "ERROR: Unit Test suite exited with code:$rc"; exit $rc
+
+  - name: periodic-kubernetes-containerd-conformance-test-s390x
     labels:
       preset-dind-enabled: "true"
       preset-ibmcloud-cred: "true"
-    decorate: true
-    decoration_config:
-      gcs_configuration:
-        bucket: ppc64le-kubernetes
-        path_strategy: explicit
-      gcs_credentials_secret: gcs-credentials
     cron: "0 2/3 * * *"
     extra_refs:
-      - base_ref: master
-        org: ppc64le-cloud
+      - base_ref: add-s390x-prov
+        org: linux-on-ibm-z
         repo: kubetest2-plugins
         workdir: true
-      - base_ref: master
-        org: kubernetes
+      - base_ref: master-1.24.1
+        org: prabhav-thali
         repo: kubernetes
     spec:
       containers:
@@ -112,43 +105,42 @@ periodics:
 
               export PATH=$GOPATH/bin:$PATH
               export GO111MODULE=on
-
+          
+              go version
 
               make install-deployer-tf
               TF_LATEST="v1.9.8"
-
-              RESOURCE_TYPE="powervs-k8s-conformance"
+          
+              RESOURCE_TYPE="vpc-service"
               USER="periodic-k8s-containerd-conformance-job"
-
+          
               trap cleanup EXIT
-
+          
               cleanup(){
                 # stop the boskos heartbeat
                 [[ -z ${HEART_BEAT_PID:-} ]] || kill -9 "${HEART_BEAT_PID}" || true
               }
-
+          
               curl -fsSL https://releases.hashicorp.com/terraform/${TF_LATEST:1}/terraform_${TF_LATEST:1}_linux_amd64.zip -o ./terraform.zip
               unzip -o ./terraform.zip  >/dev/null 2>&1
               rm -f ./terraform.zip
               TF="$PWD/terraform"
               export PATH=$PWD:$PATH
-
+          
               apt-get update && apt-get install -y ansible
-
+          
               # Details of IBM S3 storage
-              S3_SERVER=s3.us.cloud-object-storage.appdomain.cloud
-              BUCKET=k8s-infra-cos-bucket
-              DIRECTORY=ci
-
+              S3_SERVER=s3.eu.cloud-object-storage.appdomain.cloud
+              BUCKET=k8s-infra-z-eu-cos-bucket
+              DIRECTORY=conformance
+          
               # Build and push artifacts to IBM COS
-              REPOROOT=../../kubernetes/kubernetes
-              kubetest2 tf --build --repo-root $REPOROOT --stage cos://us/$BUCKET/$DIRECTORY --cos-cred-type cos_hmac
-              K8S_BUILD_VERSION=`cat $REPOROOT/_output/release-stage/server/linux-ppc64le/kubernetes/version`
-
+              REPOROOT=../../prabhav-thali/kubernetes
+              kubetest2 tf --target-provider vpc --build --target-build-arch linux/s390x --repo-root $REPOROOT --stage cos://eu/$BUCKET/$DIRECTORY --cos-cred-type cos_hmac
+              K8S_BUILD_VERSION=`cat $REPOROOT/_output/release-stage/server/linux-s390x/kubernetes/version`
+          
               TIMESTAMP=$(date +%s)
-              jq --arg key0 'k8s-build-version' --arg value0 $K8S_BUILD_VERSION '. | .[$key0]=$value0' <<<'{}' > $ARTIFACTS/metadata.json
-
-
+              jq --arg key0 'k8s-build-version' --arg value0 $K8S_BUILD_VERSION '. | .[$key0]=$value0' <<<'{}' > $ARTIFACTS/metadata.json              
               set +o errexit
 
               heartbeat_account(){
@@ -165,53 +157,59 @@ periodics:
                   sleep 60
                 done
               }
-
+          
               if [ -n "${BOSKOS_HOST:-}" ]; then
                 set +o xtrace
                 url="http://${BOSKOS_HOST}/acquire?type=${RESOURCE_TYPE}&state=free&dest=busy&owner=${USER}"
-                output=$(curl -X POST ${url})
+                output=$(curl -v -X POST ${url})
                 [ $? = 0 ] && status_code=200
-
+          
                 if [[ ${status_code} == 200 && ${output} =~ "failed" ]]; then
                   echo "Failed to acquire resource from Boskos of type ${RESOURCE_TYPE}"
                   exit 1
                 elif [[ ${status_code} == 200 ]]; then
                   export BOSKOS_RESOURCE_NAME=$(echo ${output} | jq -r '.name')
                   export BOSKOS_REGION=$(echo ${output} | jq -r '.userdata["region"]')
-                  export BOSKOS_RESOURCE_ID=$(echo ${output} | jq -r '.userdata["service-instance-id"]')
                   export BOSKOS_ZONE=$(echo ${output} | jq -r '.userdata["zone"]')
                   rm -rf output.json
                 else
                   echo "Failed to acquire resource due to invalid response, status code : ${status_code}"
                   exit 1
                 fi
-
+          
                 heartbeat_account >> "$ARTIFACTS/boskos.log" 2>&1 &
                 HEART_BEAT_PID=$(echo $!)
               fi
+          
+              echo "print variables"
+              echo ${BOSKOS_REGION}
+              echo ${BOSKOS_ZONE}
+              echo ${BOSKOS_RESOURCE_NAME}
 
-              set -o xtrace
-              kubetest2 tf --powervs-image-name CentOS-Stream-9 \
-                --powervs-region ${BOSKOS_REGION} --powervs-zone ${BOSKOS_ZONE} \
-                --powervs-service-id ${BOSKOS_RESOURCE_ID} \
-                --powervs-ssh-key k8s-infra-sshkey \
+              # set -o xtrace
+              kubetest2 tf --target-provider vpc --vpc-node-image-name ibm-ubuntu-22-04-4-minimal-s390x-3 \
+                --vpc-region ${BOSKOS_REGION} --vpc-zone ${BOSKOS_ZONE} \
+                --vpc-name ${BOSKOS_RESOURCE_NAME} \
+                --vpc-resource-group rg-conformance-test \
+                --vpc-ssh-key k8s-infra-ssh-key \
+                --vpc-node-profile bz2-4x16 \
                 --ssh-private-key /etc/secret-volume/ssh-privatekey \
                 --s3-server $S3_SERVER --bucket $BUCKET  --directory $DIRECTORY \
-                --extra-vars=k8s_tar_bundles:kubernetes-server-linux-ppc64le.tar.gz \
+                --extra-vars=k8s_tar_bundles:kubernetes-server-linux-s390x.tar.gz \
+                --extra-vars=pod_subnet:10.244.0.0/16 \
+                --extra-vars=cni_provider:flannel \
                 --build-version $K8S_BUILD_VERSION \
                 --release-marker $K8S_BUILD_VERSION \
                 --cluster-name config1-$TIMESTAMP \
                 --workers-count 2 \
                 --up --auto-approve --retry-on-tf-failure 3 \
                 --break-kubetest-on-upfail true \
-                --powervs-memory 32 \
                 --test=ginkgo -- --parallel 10 --use-built-binaries true --focus-regex='\[Conformance\]' --skip-regex='\[Serial\]'; rc1=$?
-
+          
               export KUBECONFIG="$(pwd)/config1-$TIMESTAMP/kubeconfig"
               export ARTIFACTS=$ARTIFACTS/serial_tests_artifacts
               #Run Serial Conformance tests
-              kubetest2 tf --powervs-region ${BOSKOS_REGION} --powervs-zone ${BOSKOS_ZONE} \
-                --powervs-service-id ${BOSKOS_RESOURCE_ID} \
+              kubetest2 tf --target-provider vpc --vpc-region ${BOSKOS_REGION} --vpc-zone ${BOSKOS_ZONE} \
                 --ignore-cluster-dir true \
                 --cluster-name config1-$TIMESTAMP \
                 --down --auto-approve --ignore-destroy-errors \
@@ -225,7 +223,7 @@ periodics:
                   echo "ERROR: Serial k8s Conformance tests exited with code: $rc2"
                   exit $rc2
               fi
-
+          
               if [ -n "${BOSKOS_HOST:-}" ]; then
                 url="http://${BOSKOS_HOST}/release?name=${BOSKOS_RESOURCE_NAME}&dest=dirty&owner=${USER}"
                 status_code=$(curl -w '%{http_code}' -X POST ${url})
@@ -235,21 +233,14 @@ periodics:
                 fi
               fi
 
-  - name: periodic-kubernetes-containerd-e2e-node-tests-ppc64le
+  - name: periodic-kubernetes-containerd-e2e-node-tests-s390x
     labels:
-      preset-golang-build: "true"
-      preset-ssh-bot: "true"
-    decorate: true
-    decoration_config:
-      gcs_configuration:
-        bucket: ppc64le-kubernetes
-        path_strategy: explicit
-      gcs_credentials_secret: gcs-credentials
+      preset-e2e-test: "true"
       timeout: 2h
-    cron: "0 3/3 * * *"
+    cron: "0 1/1 * * *"
     extra_refs:
-      - base_ref: master
-        org: ppc64le-cloud
+      - base_ref: add-s390x-prov
+        org: linux-on-ibm-z
         repo: kubetest2-plugins
         workdir: true
     spec:
@@ -273,7 +264,6 @@ periodics:
               export PATH=$GOPATH/bin:$PATH
               export GO111MODULE=on
 
-
               make install-deployer-tf
 
               TF_LATEST="v1.9.8"
@@ -295,23 +285,23 @@ periodics:
               chmod +x /usr/local/bin/kubectl
 
               set +o errexit
-              kubetest2 tf --powervs-dns k8s-tests \
-                --powervs-image-name CentOS-Stream-9 \
-                --powervs-region syd --powervs-zone syd05 \
-                --powervs-service-id c3f5354a-517e-4927-8523-890c4bf3d6c5 \
-                --powervs-ssh-key powercloud-bot-key \
+              kubetest2 tf --target-provider vpc --vpc-node-image-name ibm-ubuntu-22-04-4-minimal-s390x-3 \
+                --vpc-name node-e2e-tests-vpc \
+                --vpc-region eu-de --vpc-zone eu-de-1 \
+                --vpc-resource-group rg-e2e-test \
+                --vpc-ssh-key k8s-e2e-test \
+                --vpc-node-profile bz2-4x16 \
                 --ssh-private-key /etc/secret-volume/ssh-privatekey \
                 --cluster-name config3-$TIMESTAMP \
                 --up --set-kubeconfig=false --auto-approve \
                 --build-version $K8S_BUILD_VERSION --retry-on-tf-failure 3 \
-                --break-kubetest-on-upfail true --powervs-memory 32 \
+                --break-kubetest-on-upfail true \
                 --playbook k8s-node-remote.yml
               EXTERNAL_IP=`grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' $(pwd)/config3-$TIMESTAMP/hosts`
-              kubetest2 tf --test=exec -- ssh -i /etc/secret-volume/ssh-privatekey root@$EXTERNAL_IP \
+              kubetest2 tf --target-provider vpc --test=exec -- ssh -i /etc/secret-volume/ssh-privatekey root@$EXTERNAL_IP \
                 "export SKIP='\[Flaky\]|\[Slow\]|\[Serial\]|Containers.Lifecycle.should|should.execute.readiness.probe.while.in.preStop' && /make-test-e2e-node.sh"; \
                 rc=$?; scp -r -i /etc/secret-volume/ssh-privatekey root@$EXTERNAL_IP:/tmp/_artifacts $ARTIFACTS
-              kubetest2 tf --powervs-region syd --powervs-zone syd05 \
-                --powervs-service-id c3f5354a-517e-4927-8523-890c4bf3d6c5 \
+              kubetest2 tf --target-provider vpc --vpc-region eu-de --vpc-zone eu-de-1 \
                 --ignore-cluster-dir true \
                 --cluster-name config3-$TIMESTAMP \
                 --down --auto-approve --ignore-destroy-errors
