Update the order of jobs.

diff --git a/config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml b/config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
--- a/config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
+++ b/config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
@@ -23,6 +23,156 @@ periodics:
               cpu: 3
               memory: "12Gi"
 
+  - name: ci-kubernetes-s390x-conformance-latest-kubetest2
+    interval: 3h
+    labels:
+      preset-ibmcloud-cred: "true"
+    decorate: true
+    decoration_config:
+      timeout: 220m
+    extra_refs:
+      - base_ref: vpc-s390x-test
+        org: linux-on-ibm-z
+        repo: provider-ibmcloud-test-infra
+        workdir: true
+    annotations:
+      description: Runs conformance tests using kubetest2 against kubernetes ci latest on IBM VPC
+    spec:
+      containers:
+        - image: quay.io/prabhavthali/kubekins-e2e-v2:20250508-v2
+          securityContext:
+            privileged: true
+          env:
+            - name: "BOSKOS_HOST"
+              value: "boskos.test-pods.svc.cluster.local"
+            - name: "USER"
+              value: "ci-kubernetes-s390x-conformance-latest-kubetest2"
+          resources:
+            requests:
+              cpu: 3
+              memory: "14Gi"
+            limits:
+              cpu: 3
+              memory: "14Gi"
+          command:
+            - runner.sh
+          args:
+            - bash
+            - -c
+            - |
+              set -o errexit
+              set -o nounset
+              set -o pipefail
+              set -o xtrace
+
+              export PATH=$GOPATH/bin:$PATH
+              export GO111MODULE=on
+              RESOURCE_TYPE="vpc-service"
+              kubetest2 --version
+              #Call to boskos to checkout resource
+              heartbeat_account(){
+                count=0
+                url="http://${BOSKOS_HOST}/update?name=${BOSKOS_RESOURCE_NAME}&state=busy&owner=${USER}"
+                while [ ${count} -lt 120 ]
+                do
+                  status_code=$(curl -s -o /dev/null -w '%{http_code}' -X POST ${url})
+                  if [[ ${status_code} != 200 ]]; then
+                    echo "Heart beat to resource '${BOSKOS_RESOURCE_NAME}' failed due to invalid response, status code: ${status_code}"
+                    exit 1
+                  fi
+                  count=$(( $count + 1 ))
+                  sleep 60
+                done
+              }
+
+              if [ -n "${BOSKOS_HOST:-}" ]; then
+                set +o xtrace
+                url="http://${BOSKOS_HOST}/acquire?type=${RESOURCE_TYPE}&state=free&dest=busy&owner=${USER}"
+                output=$(curl -v -X POST ${url})
+                [ $? = 0 ] && status_code=200
+
+                if [[ ${status_code} == 200 && ${output} =~ "failed" ]]; then
+                  echo "Failed to acquire resource from Boskos of type ${RESOURCE_TYPE}"
+                  exit 1
+                elif [[ ${status_code} == 200 ]]; then
+                  export BOSKOS_RESOURCE_NAME=$(echo ${output} | jq -r '.name')
+                  export BOSKOS_REGION=$(echo ${output} | jq -r '.userdata["region"]')
+                  export BOSKOS_RG=$(echo ${output} | jq -r '.userdata["resource-group"]')
+                  export BOSKOS_ZONE=$(echo ${output} | jq -r '.userdata["zone"]')
+                  rm -rf output.json
+                else
+                  echo "Failed to acquire resource due to invalid response, status code : ${status_code}"
+                  exit 1
+                fi
+
+                heartbeat_account >> "$ARTIFACTS/boskos.log" 2>&1 &
+                HEART_BEAT_PID=$(echo $!)
+              fi
+
+              echo "Resource Name:"
+              echo ${BOSKOS_RESOURCE_NAME}
+              echo ${BOSKOS_RG}
+              echo ${BOSKOS_ZONE}
+
+              #Setup of kubetest2 tf deployer and ginkgo tester
+              make install-deployer-tf
+              go install sigs.k8s.io/kubetest2/kubetest2-tester-ginkgo@latest
+
+              #Install ansible required to bring up k8s cluster on infra
+              apt-get update && apt-get install -y ansible
+
+              K8S_BUILD_VERSION=$(curl https://storage.googleapis.com/k8s-release-dev/ci/latest.txt)
+
+              TIMESTAMP=$(date +%s)
+
+              set +o errexit
+              set -o xtrace
+              kubetest2 tf --target-provider vpc --vpc-node-image-name ibm-ubuntu-22-04-4-minimal-s390x-3 \
+                --vpc-region ${BOSKOS_REGION} --vpc-zone ${BOSKOS_ZONE} \
+                --vpc-name ${BOSKOS_RESOURCE_NAME} \
+                --vpc-resource-group rZVPCcloudRG \
+                --vpc-ssh-key prabhav-loz \
+                --vpc-node-profile bz2-4x16 \
+                --ssh-private-key /etc/secret-volume/ssh-privatekey \
+                --extra-vars=k8s_tar_bundles:kubernetes-server-linux-s390x.tar.gz \
+                --extra-vars=pod_subnet:10.244.0.0/16 \
+                --extra-vars=cni_provider:flannel \
+                --build-version $K8S_BUILD_VERSION \
+                --release-marker $K8S_BUILD_VERSION \
+                --cluster-name config1-$TIMESTAMP \
+                --workers-count 2 \
+                --up --auto-approve --retry-on-tf-failure 3 \
+                --break-kubetest-on-upfail true \
+                --test=ginkgo -- --parallel 10 --test-package-dir ci --test-package-version $K8S_BUILD_VERSION --focus-regex='\[Conformance\]' --skip-regex='\[Serial\]'; rc1=$?
+
+              export KUBECONFIG="$(pwd)/config1-$TIMESTAMP/kubeconfig"
+              export ARTIFACTS=$ARTIFACTS/serial_tests_artifacts
+              #Run Serial Conformance tests
+              kubetest2 tf --target-provider vpc --vpc-region ${BOSKOS_REGION} --vpc-zone ${BOSKOS_ZONE} \
+                --ignore-cluster-dir true \
+                --cluster-name config1-$TIMESTAMP \
+                --down --auto-approve --ignore-destroy-errors \
+                --test=ginkgo -- \
+                --test-package-dir ci \
+                --test-package-version $K8S_BUILD_VERSION --focus-regex='\[Serial\].*\[Conformance\]'; rc2=$?
+
+              if [ -n "${BOSKOS_HOST:-}" ]; then
+                url="http://${BOSKOS_HOST}/release?name=${BOSKOS_RESOURCE_NAME}&dest=dirty&owner=${USER}"
+                status_code=$(curl -w '%{http_code}' -X POST ${url})
+                if [[ ${status_code} != 200 ]]; then
+                  echo "Failed to release resource: ${BOSKOS_RESOURCE_NAME}"
+                  exit 1
+                fi
+              fi
+
+              if [ $rc1 != 0 ]; then
+                  echo "ERROR: Non Serial k8s Conformance tests exited with code: $rc1"
+                  exit $rc1
+              elif [ $rc2 != 0 ]; then
+                  echo "ERROR: Serial k8s Conformance tests exited with code: $rc2"
+                  exit $rc2
+              fi
+
   - name: periodic-kubernetes-unit-test-s390x
     cron: "0 1/3 * * *"
     labels: 
@@ -256,157 +406,6 @@ periodics:
                   exit 1
                 fi
               fi
-
-  - name: ci-kubernetes-s390x-conformance-latest-kubetest2
-    interval: 3h
-    labels:
-      preset-ibmcloud-cred: "true"
-    decorate: true
-    decoration_config:
-      timeout: 220m
-    extra_refs:
-      - base_ref: vpc-s390x-test
-        org: linux-on-ibm-z
-        repo: provider-ibmcloud-test-infra
-        workdir: true
-    annotations:
-      description: Runs conformance tests using kubetest2 against kubernetes ci latest on IBM VPC
-    spec:
-      containers:
-        - image: quay.io/prabhavthali/kubekins-e2e-v2:20250508-v2
-          securityContext:
-            privileged: true
-          env:
-            - name: "BOSKOS_HOST"
-              value: "boskos.test-pods.svc.cluster.local"
-            - name: "USER"
-              value: "ci-kubernetes-s390x-conformance-latest-kubetest2"
-          resources:
-            requests:
-              cpu: 3
-              memory: "14Gi"
-            limits:
-              cpu: 3
-              memory: "14Gi"
-          command:
-            - runner.sh
-          args:
-            - bash
-            - -c
-            - |
-              set -o errexit
-              set -o nounset
-              set -o pipefail
-              set -o xtrace
-
-              export PATH=$GOPATH/bin:$PATH
-              export GO111MODULE=on
-              RESOURCE_TYPE="vpc-service"
-              kubetest2 --version
-              #Call to boskos to checkout resource
-              heartbeat_account(){
-                count=0
-                url="http://${BOSKOS_HOST}/update?name=${BOSKOS_RESOURCE_NAME}&state=busy&owner=${USER}"
-                while [ ${count} -lt 120 ]
-                do
-                  status_code=$(curl -s -o /dev/null -w '%{http_code}' -X POST ${url})
-                  if [[ ${status_code} != 200 ]]; then
-                    echo "Heart beat to resource '${BOSKOS_RESOURCE_NAME}' failed due to invalid response, status code: ${status_code}"
-                    exit 1
-                  fi
-                  count=$(( $count + 1 ))
-                  sleep 60
-                done
-              }
-
-              if [ -n "${BOSKOS_HOST:-}" ]; then
-                set +o xtrace
-                url="http://${BOSKOS_HOST}/acquire?type=${RESOURCE_TYPE}&state=free&dest=busy&owner=${USER}"
-                output=$(curl -v -X POST ${url})
-                [ $? = 0 ] && status_code=200
-
-                if [[ ${status_code} == 200 && ${output} =~ "failed" ]]; then
-                  echo "Failed to acquire resource from Boskos of type ${RESOURCE_TYPE}"
-                  exit 1
-                elif [[ ${status_code} == 200 ]]; then
-                  export BOSKOS_RESOURCE_NAME=$(echo ${output} | jq -r '.name')
-                  export BOSKOS_REGION=$(echo ${output} | jq -r '.userdata["region"]')
-                  export BOSKOS_RG=$(echo ${output} | jq -r '.userdata["resource-group"]')
-                  export BOSKOS_ZONE=$(echo ${output} | jq -r '.userdata["zone"]')
-                  rm -rf output.json
-                else
-                  echo "Failed to acquire resource due to invalid response, status code : ${status_code}"
-                  exit 1
-                fi
-
-                heartbeat_account >> "$ARTIFACTS/boskos.log" 2>&1 &
-                HEART_BEAT_PID=$(echo $!)
-              fi
-
-              echo "Resource Name:"
-              echo ${BOSKOS_RESOURCE_NAME}
-              echo ${BOSKOS_RG}
-              echo ${BOSKOS_ZONE}
-
-              #Setup of kubetest2 tf deployer and ginkgo tester
-              make install-deployer-tf
-              go install sigs.k8s.io/kubetest2/kubetest2-tester-ginkgo@latest
-
-              #Install ansible required to bring up k8s cluster on infra
-              apt-get update && apt-get install -y ansible
-
-              K8S_BUILD_VERSION=$(curl https://storage.googleapis.com/k8s-release-dev/ci/latest.txt)
-
-              TIMESTAMP=$(date +%s)
-
-              set +o errexit
-              set -o xtrace
-              kubetest2 tf --target-provider vpc --vpc-node-image-name ibm-ubuntu-22-04-4-minimal-s390x-3 \
-                --vpc-region ${BOSKOS_REGION} --vpc-zone ${BOSKOS_ZONE} \
-                --vpc-name ${BOSKOS_RESOURCE_NAME} \
-                --vpc-resource-group rZVPCcloudRG \
-                --vpc-ssh-key prabhav-loz \
-                --vpc-node-profile bz2-4x16 \
-                --ssh-private-key /etc/secret-volume/ssh-privatekey \
-                --extra-vars=k8s_tar_bundles:kubernetes-server-linux-s390x.tar.gz \
-                --extra-vars=pod_subnet:10.244.0.0/16 \
-                --extra-vars=cni_provider:flannel \
-                --build-version $K8S_BUILD_VERSION \
-                --release-marker $K8S_BUILD_VERSION \
-                --cluster-name config1-$TIMESTAMP \
-                --workers-count 2 \
-                --up --auto-approve --retry-on-tf-failure 3 \
-                --break-kubetest-on-upfail true \
-                --test=ginkgo -- --parallel 10 --test-package-dir ci --test-package-version $K8S_BUILD_VERSION --focus-regex='\[Conformance\]' --skip-regex='\[Serial\]'; rc1=$?
-
-              export KUBECONFIG="$(pwd)/config1-$TIMESTAMP/kubeconfig"
-              export ARTIFACTS=$ARTIFACTS/serial_tests_artifacts
-              #Run Serial Conformance tests
-              kubetest2 tf --target-provider vpc --vpc-region ${BOSKOS_REGION} --vpc-zone ${BOSKOS_ZONE} \
-                --ignore-cluster-dir true \
-                --cluster-name config1-$TIMESTAMP \
-                --down --auto-approve --ignore-destroy-errors \
-                --test=ginkgo -- \
-                --test-package-dir ci \
-                --test-package-version $K8S_BUILD_VERSION --focus-regex='\[Serial\].*\[Conformance\]'; rc2=$?
-
-              if [ -n "${BOSKOS_HOST:-}" ]; then
-                url="http://${BOSKOS_HOST}/release?name=${BOSKOS_RESOURCE_NAME}&dest=dirty&owner=${USER}"
-                status_code=$(curl -w '%{http_code}' -X POST ${url})
-                if [[ ${status_code} != 200 ]]; then
-                  echo "Failed to release resource: ${BOSKOS_RESOURCE_NAME}"
-                  exit 1
-                fi
-              fi
-
-              if [ $rc1 != 0 ]; then
-                  echo "ERROR: Non Serial k8s Conformance tests exited with code: $rc1"
-                  exit $rc1
-              elif [ $rc2 != 0 ]; then
-                  echo "ERROR: Serial k8s Conformance tests exited with code: $rc2"
-                  exit $rc2
-              fi
-
   - name: periodic-kubernetes-containerd-e2e-node-tests-s390x
     labels:
       preset-e2e-test: "true"
